logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging.level.sql: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subsidy_dictionaries
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  flyway:
    enabled: true
    locations: |
      classpath:db/migration/version1/common,classpath:db/migration/version1/test-data,classpath:db/migration/version1/postgresql
    out-of-order: false