apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: subsidy-back-dictionaries
  name: subsidy-back-dictionaries
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: subsidy-back-dictionaries
  sessionAffinity: None
  type: ClusterIP
