apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: subsidy-back-dictionaries-secret-template
  labels:
    type: services
objects:
  - apiVersion: v1
    data:
      password: ${postgres_subsidydb_password}
      username: ${postgres_subsidydb_username}
    kind: Secret
    metadata:
      labels:
        app: subsidy-back-dictionaries
      name: subsidy-back-dictionaries-db-secret
    type: Opaque

parameters:
  - name: postgres_dictionaries_username
    description: postgres_dictionaries_username
    required: true
  - name: postgres_dictionaries_password
    description: postgres_dictionaries_password
    required: true